#include "config.h"
#ifdef ANDROID_V
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xtc_audio_util_Opus */

#ifndef _com_xtc_audio_util_OpusEncoder
#define _com_xtc_audio_util_OpusEncoder
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_xtc_audio_util_OpusDecoder_init
    (JNIEnv *env, jobject obj,jint sampleRate);

JNIEXPORT void JNICALL Java_com_xtc_audio_util_OpusDecoder_exit
    (JNIEnv *env, jobject obj,jint handle);

JNIEXPORT jint Java_com_xtc_audio_util_OpusDecoder_decode
            (JNIEnv *env, jobject obj,jint handle,jbyteArray opus,jint opusSize,jbyteArray out,jint frame_size);

#ifdef __cplusplus
}
#endif
#endif

#endif 
