#include "config.h"
#ifdef ANDROID_V
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xtc_audio_util_Opus */

#ifndef _com_xtc_audio_util_OpusEncoder
#define _com_xtc_audio_util_OpusEncoder
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_xtc_audio_util_OpusEncoder_init
    (JNIEnv *env, jobject obj,jint sampleRate,jint bitRate);

JNIEXPORT void JNICALL Java_com_xtc_audio_util_OpusEncoder_exit
    (JNIEnv *env, jobject obj,jlong handle);

JNIEXPORT jint Java_com_xtc_audio_util_OpusEncoder_encode
    (JNIEnv *env, jobject obj,jlong handle,jbyteArray pcm,int frame_size,jbyteArray data,jint max_data_bytes);

#ifdef __cplusplus
}
#endif
#endif

#endif 
